/**
 * `runtime.lock.json` — the pinned description of a fetched runtime, plus `--check`
 * verification and the generated THIRD-PARTY.md.
 *
 * Lock shape (version 1):
 * {
 *   version, target, createdAt, sources: { node: {...}, python: {...} },
 *   artifacts: [ { name, url, sha256, bytes, verifiedBy } ],
 *   wheels:    [ { name, version, filename, sha256 } ],
 *   blocks:    { node|python|wheels: { files, bytes, sha256 } }
 * }
 *
 * `blocks.*.sha256` is the manifest digest (see lib/hash.mjs): it changes when any
 * file is added, removed or modified, so `--check` can verify a runtime in place
 * without a per-file map in the lock.
 */

import * as fs from 'node:fs'
import * as path from 'node:path'
import { blockSummary, formatBytes } from './hash.mjs'

export const RUNTIME_LOCK_VERSION = 1
export const BLOCK_NAMES = ['node', 'python', 'wheels']

export function runtimePaths(outDir) {
  return {
    root: outDir,
    node: path.join(outDir, 'node'),
    python: path.join(outDir, 'python'),
    wheels: path.join(outDir, 'wheels'),
    sitePackages: path.join(outDir, 'python', 'Lib', 'site-packages'),
  }
}

export function readRuntimeLock(file) {
  const lock = JSON.parse(fs.readFileSync(file, 'utf8'))
  if (lock.version !== RUNTIME_LOCK_VERSION) {
    throw new Error(`Unsupported runtime lock version ${lock.version} in ${file}`)
  }
  return lock
}

export function writeRuntimeLock(file, lock) {
  fs.mkdirSync(path.dirname(file), { recursive: true })
  fs.writeFileSync(file, `${JSON.stringify(lock, null, 2)}\n`, 'utf8')
  return file
}

export async function buildRuntimeLock({ target, sources, artifacts, wheels, outDir }) {
  const paths = runtimePaths(outDir)
  const blocks = {}
  for (const name of BLOCK_NAMES) {
    const dir = paths[name]
    if (!fs.existsSync(dir)) throw new Error(`Runtime block "${name}" is missing at ${dir}`)
    blocks[name] = await blockSummary(dir)
  }
  return {
    version: RUNTIME_LOCK_VERSION,
    target,
    createdAt: new Date().toISOString(),
    sources,
    artifacts,
    wheels,
    blocks,
  }
}

/**
 * Verify an existing runtime against the lock, without touching the network.
 * Reports every block with the expected/actual summary and a short diff description.
 */
export async function verifyRuntime(lock, outDir) {
  const paths = runtimePaths(outDir)
  const results = []
  for (const name of BLOCK_NAMES) {
    const expected = lock.blocks?.[name]
    const dir = paths[name]
    if (!expected) {
      results.push({ name, dir, ok: false, detail: 'the lock has no summary for this block', expected: null, actual: null })
      continue
    }
    if (!fs.existsSync(dir)) {
      results.push({ name, dir, ok: false, detail: 'directory is missing', expected, actual: null })
      continue
    }
    const actual = await blockSummary(dir)
    const ok = actual.files === expected.files && actual.bytes === expected.bytes && actual.sha256 === expected.sha256
    let detail = 'matches the lock'
    if (!ok) {
      const fileDelta = actual.files - expected.files
      const byteDelta = actual.bytes - expected.bytes
      detail = [
        `manifest digest ${actual.sha256.slice(0, 12)}… != ${expected.sha256.slice(0, 12)}…`,
        `files ${actual.files} (${fileDelta >= 0 ? '+' : ''}${fileDelta})`,
        `bytes ${actual.bytes} (${byteDelta >= 0 ? '+' : ''}${byteDelta})`,
        'the runtime is stale or tampered — re-run fetch-runtime.mjs to repair',
      ].join(', ')
    }
    results.push({ name, dir, ok, detail, expected, actual })
  }
  return { ok: results.every((result) => result.ok), target: lock.target, results }
}

/** Parse the `METADATA` of a wheel: name, version and the license line if present. */
export function parseWheelMetadata(metadataText) {
  const fields = {}
  for (const line of metadataText.split(/\r?\n/)) {
    const match = /^([A-Za-z-]+):\s*(.*)$/.exec(line)
    if (match && fields[match[1].toLowerCase()] === undefined) fields[match[1].toLowerCase()] = match[2].trim()
  }
  return {
    name: fields.name ?? 'unknown',
    version: fields.version ?? 'unknown',
    license: fields.license && fields.license !== 'UNKNOWN' ? fields.license : null,
    classifier: null,
  }
}

export function renderThirdParty(lock) {
  const lines = [
    '# Third-party software bundled with BoxFox Desktop (Alpha)',
    '',
    `Generated by \`desktop/scripts/fetch-runtime.mjs\` for target \`${lock.target}\` on ${lock.createdAt}.`,
    'Do not edit by hand — regenerate the runtime to update this file.',
    '',
    '## Runtime artifacts',
    '',
    '| Component | Version | SHA-256 | License |',
    '|---|---|---|---|',
  ]
  for (const artifact of lock.artifacts) {
    lines.push(`| ${artifact.name} | ${artifact.version ?? '-'} | \`${artifact.sha256}\` | ${artifact.license ?? 'see upstream'} |`)
  }
  lines.push('', '## Python wheels', '', '| Package | Version | File | SHA-256 | License |', '|---|---|---|---|---|')
  for (const wheel of lock.wheels) {
    lines.push(`| ${wheel.name} | ${wheel.version} | \`${wheel.filename}\` | \`${wheel.sha256}\` | ${wheel.license ?? 'see package metadata'} |`)
  }
  const totalBytes = Object.values(lock.blocks).reduce((total, block) => total + block.bytes, 0)
  lines.push(
    '',
    '## Blocks',
    '',
    '| Block | Files | Size | Manifest SHA-256 |',
    '|---|---|---|---|',
  )
  for (const [name, block] of Object.entries(lock.blocks)) {
    lines.push(`| ${name} | ${block.files} | ${formatBytes(block.bytes)} | \`${block.sha256}\` |`)
  }
  lines.push('', `Total: ${formatBytes(totalBytes)}.`, '')
  return lines.join('\n')
}
